# Generated by Django 4.0.6 on 2022-08-21 11:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('blog_api', '0004_alter_note_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='note',
            name='read_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='blog_api.profile'),
        ),
    ]
