# Generated by Django 4.0.6 on 2022-08-21 14:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog_api', '0006_remove_note_read_by_note_read_by'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='note',
            name='read_by',
        ),
        migrations.AddField(
            model_name='profile',
            name='read_posts',
            field=models.ManyToManyField(blank=True, to='blog_api.note'),
        ),
    ]
