# Generated by Django 4.0.6 on 2022-08-21 16:14

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('blog_api', '0007_remove_note_read_by_profile_read_posts'),
    ]

    operations = [
        migrations.AddField(
            model_name='note',
            name='read_user',
            field=models.ManyToManyField(blank=True, related_name='view', to=settings.AUTH_USER_MODEL),
        ),
    ]
